#! /bin/sh

#mainmonitor="$(bspc query --monitors --names | grep -v LVDS)"

#if ! [ -z "$mainmonitor" ]; then
    #xrandr --output "$mainmonitor" --auto --output LVDS-1 --off
#else
    #mainmonitor="LVDS-1"
#fi

bspc monitor "HDMI-A-0" -d 1 2 3 4 5 6 7 8 9 10
#bspc desktop -f 1

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#############
## startup ##
#############

#xrdb -load ~/.Xresources &

pkill sxhkd
sxhkd &

feh --bg-center $HOME/pictures/wallpaper/forest.jpg

panel #polybar script

notifi #notification-center

###########
## rules ##
###########

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop=2
bspc rule -a Thunar state=floating
bspc rule -a Steam state=floating
bspc rule -a Fightcade state=floating
bspc rule -a fcadefbneo.exe state=floating
bspc rule -a Brave-browser desktop=2
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a "Picture in picture" state=floating
