#!/bin/zsh
# vim: filetype=sh

sel=$(echo "🗘 reboot\n⏻ shutdown" | rofi -dmenu -theme powermenu)

if [ "$sel" = "🗘 reboot" ]; then
    reboot
elif [ "$sel" = "⏻ shutdown" ]; then
    shutdown now
fi

